  
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: CmdLine@2
  inputs:
    script: 'make all' 

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: CmdLine@2
  inputs:
    script: 'make image'

- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'docker login $(Host) -u $(Username) -p $(Password)'
    
- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'make push'
    
