  
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: CmdLine@2
  inputs:
    script: 'make build-env' 

- task: CmdLine@2
  inputs:
    script: 'make all' 

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'docker login $(Host) -u $(Username) -p $(Password)'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'azure-sonarqube'
    scannerMode: 'CLI'
    configMode: 'file'
    
- task: CmdLine@2
  inputs:
    script: 'make sonar' 

- task: SonarQubePublish@4

  inputs:
    pollingTimeoutSec: '300'
- task: CmdLine@2
  inputs:
    script: 'make build-vlol'

- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'make push'
    
